## Alumno: Aldo Yerico Mendoza Cotera
## Codigo: 20191315

In [1]:
import pandas as pd

### Fuente del dataset
https://www.kaggle.com/russellyates88/suicide-rates-overview-1985-to-2016?select=master.csv

In [2]:
data = pd.read_csv("D:\Cursos Q-LAB\Python\Trabajo final\datafinal\master.csv")

In [3]:
data

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers
...,...,...,...,...,...,...,...,...,...,...,...,...
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers

## OJO
En esta primera parte de manipulaciÃ³n y transformacion de datos no eliminarÃ© ningpun valor perdido ya que, al tratarse de suicidios, casi todos los aÃ±os los hay y eliminar valores perdidos me llevaria a eliminar filas o columnas de las que no quisiera prescindir. A esto aÃ±adirle que se sabe que los comandos para obtener estadÃ­sticos descriptivos omite por defecto los valores perdidos: por lo cual no se verÃ¡n afectados los datos ni los resultados obtenidos de Ã©stos.

### Primeras 5 observaciones del dataset
Uso el comando "head()".

In [4]:
data.head()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers

### Ultimas 5 observaciones del dataset
Uso el comando "tail()".

In [5]:
data.tail()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers

### Informacion de las variables
Uso el comando "info()" para obtener un resumen de la informacion de cada variable del dataset.

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27820 entries, 0 to 27819
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   country             27820 non-null  object
 1   year                27820 non-null  int64
 2   sex                 27820 non-null  object
 3   age                 27820 non-null  object
 4   suicides_no         27820 non-null  int64
 5   population          27820 non-null  int64
 6   suicides/100k pop   27820 non-null  float64
 7   country-year        27820 non-null  object
 8   HDI for year        8364 non-null   float64
 9    gdp_for_year ($)   27820 non-null  object
 10  gdp_per_capita ($)  27820 non-null  int64
 11  generation          27820 non-null  object
dtypes: float64(2), int64(4), object(6)
memory usage: 2.5+ MB

### TamaÃ±o del dataset
Uso el comando "shape()"

In [7]:
data.shape

(27820, 12)

### Estadisticos descriptivos
Uso el comando "describe()" para obtener los principales medidas de tendencia central de las variables.

In [8]:
data.describe()

,year,suicides_no,population,suicides/100k pop,HDI for year,gdp_per_capita ($)
count,27820.000000,27820.000000,2.782000e+04,27820.000000,8364.000000,27820.000000
mean,2001.258375,242.574407,1.844794e+06,12.816097,0.776601,16866.464414
std,8.469055,902.047917,3.911779e+06,18.961511,0.093367,18887.576472
min,1985.000000,0.000000,2.780000e+02,0.000000,0.483000,251.000000
25%,1995.000000,3.000000,9.749850e+04,0.920000,0.713000,3447.000000
50%,2002.000000,25.000000,4.301500e+05,5.990000,0.779000,9372.000000
75%,2008.000000,131.000000,1.486143e+06,16.620000,0.855000,24874.000000
max,2016.000000,22338.000000,4.380521e+07,224.970000,0.944000,126352.000000

### Ordenando la data
Uso el comando "sor_values" para ordenar descendentemente y ver los suicidios en aquellos paises con mayor HDI (Indice de Desarrollo Humano) y mayor PBI per capita.

In [9]:
data.sort_values(['HDI for year', 'gdp_per_capita ($)'],ascending = False,  inplace = True)
data.head(10)

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
18204,Norway,2014,male,75+ years,33,143089,23.06,Norway2014,0.944,"499,338,534,779",103443,Silent
18205,Norway,2014,male,55-74 years,110,532578,20.65,Norway2014,0.944,"499,338,534,779",103443,Boomers
18206,Norway,2014,male,35-54 years,147,732244,20.08,Norway2014,0.944,"499,338,534,779",103443,Generation X
18207,Norway,2014,male,25-34 years,71,353943,20.06,Norway2014,0.944,"499,338,534,779",103443,Millenials
18208,Norway,2014,male,15-24 years,38,344245,11.04,Norway2014,0.944,"499,338,534,779",103443,Millenials
18209,Norway,2014,female,55-74 years,51,533630,9.56,Norway2014,0.944,"499,338,534,779",103443,Boomers
18210,Norway,2014,female,35-54 years,51,688993,7.40,Norway2014,0.944,"499,338,534,779",103443,Generation X
18211,Norway,2014,female,25-34 years,20,337592,5.92,Norway2014,0.944,"499,338,534,779",103443,Millenials
18212,Norway,2014,female,15-24 years,17,325164,5.23,Norway2014,0.944,"499,338,534,779",103443,Millenials
18213,Norway,2014,female,75+ years,7,214335,3.27,Norway2014,0.944,"499,338,534,779",103443,Silent

### Cambiando de nombre algunas variables

Cambiare de nombre algunas variables definiendo un diccionario y luego usando el comando "rename". Esto lo hago para simplificar la entrada de comandos en la siguientes lineas.

In [10]:
nombres = {'suicides_no': 'suicides', 'HDI for year' : 'hdi', '  gdp_for_year ($)  ' : 'gdpy', 'gdp_per_capita ($)' : 'gdpc'}
data.rename(columns = nombres, inplace = True)

In [11]:
data

,country,year,sex,age,suicides,population,suicides/100k pop,country-year,hdi,gdp_for_year ($),gdpc,generation
18204,Norway,2014,male,75+ years,33,143089,23.06,Norway2014,0.944,"499,338,534,779",103443,Silent
18205,Norway,2014,male,55-74 years,110,532578,20.65,Norway2014,0.944,"499,338,534,779",103443,Boomers
18206,Norway,2014,male,35-54 years,147,732244,20.08,Norway2014,0.944,"499,338,534,779",103443,Generation X
18207,Norway,2014,male,25-34 years,71,353943,20.06,Norway2014,0.944,"499,338,534,779",103443,Millenials
18208,Norway,2014,male,15-24 years,38,344245,11.04,Norway2014,0.944,"499,338,534,779",103443,Millenials
...,...,...,...,...,...,...,...,...,...,...,...,...
43,Albania,1992,female,55-74 years,1,164900,0.61,Albania1992,NaN,"709,452,584",251,Silent
44,Albania,1992,female,5-14 years,0,336700,0.00,Albania1992,NaN,"709,452,584",251,Millenials
45,Albania,1992,female,75+ years,0,38700,0.00,Albania1992,NaN,"709,452,584",251,G.I. Generation
46,Albania,1992,male,5-14 years,0,362900,0.00,Albania1992,NaN,"709,452,584",251,Millenials
47,Albania,1992,male,75+ years,0,23900,0.00,Albania1992,NaN,"709,452,584",251,G.I. Generation

### Noruega al 2014
Me interesa Noruega al ser el pais con mayor HDI y GDP a nivel mundial hasta el 2014 (se lo podria calificar como el "mejor" pais del mundo). Para ello filtro los datos por aÃ±o y pais con "&".

In [12]:
noruegos2014 = data[(data["country"] == 'Norway') & (data["year"] == 2014)]

In [13]:
noruegos2014

,country,year,sex,age,suicides,population,suicides/100k pop,country-year,hdi,gdp_for_year ($),gdpc,generation
18204,Norway,2014,male,75+ years,33,143089,23.06,Norway2014,0.944,"499,338,534,779",103443,Silent
18205,Norway,2014,male,55-74 years,110,532578,20.65,Norway2014,0.944,"499,338,534,779",103443,Boomers
18206,Norway,2014,male,35-54 years,147,732244,20.08,Norway2014,0.944,"499,338,534,779",103443,Generation X
18207,Norway,2014,male,25-34 years,71,353943,20.06,Norway2014,0.944,"499,338,534,779",103443,Millenials
18208,Norway,2014,male,15-24 years,38,344245,11.04,Norway2014,0.944,"499,338,534,779",103443,Millenials
18209,Norway,2014,female,55-74 years,51,533630,9.56,Norway2014,0.944,"499,338,534,779",103443,Boomers
18210,Norway,2014,female,35-54 years,51,688993,7.40,Norway2014,0.944,"499,338,534,779",103443,Generation X
18211,Norway,2014,female,25-34 years,20,337592,5.92,Norway2014,0.944,"499,338,534,779",103443,Millenials
18212,Norway,2014,female,15-24 years,17,325164,5.23,Norway2014,0.944,"499,338,534,779",103443,Millenials
18213,Norway,2014,female,75+ years,7,214335,3.27,Norway2014,0.944,"499,338,534,779",103443,Silent
18214,Norway,2014,male,5-14 years,2,317878,0.63,Norway2014,0.944,"499,338,534,779",103443,Generation Z
18215,Norway,2014,female,5-14 years,1,303487,0.33,Norway2014,0.944,"499,338,534,779",103443,Generation Z

### Noruega en 1986

In [14]:
noruegos1986 = data[(data["country"] == 'Norway') & (data["year"] == 1986)]

In [15]:
noruegos1986

,country,year,sex,age,suicides,population,suicides/100k pop,country-year,hdi,gdp_for_year ($),gdpc,generation
17868,Norway,1986,male,35-54 years,137,500900,27.35,Norway1986,NaN,"78,693,253,276",20117,Silent
17869,Norway,1986,male,25-34 years,86,318200,27.03,Norway1986,NaN,"78,693,253,276",20117,Boomers
17870,Norway,1986,male,55-74 years,101,383100,26.36,Norway1986,NaN,"78,693,253,276",20117,G.I. Generation
17871,Norway,1986,male,15-24 years,69,336000,20.54,Norway1986,NaN,"78,693,253,276",20117,Generation X
17872,Norway,1986,male,75+ years,19,102800,18.48,Norway1986,NaN,"78,693,253,276",20117,G.I. Generation
17873,Norway,1986,female,35-54 years,67,480100,13.96,Norway1986,NaN,"78,693,253,276",20117,Silent
17874,Norway,1986,female,55-74 years,56,430100,13.02,Norway1986,NaN,"78,693,253,276",20117,G.I. Generation
17875,Norway,1986,female,75+ years,10,173700,5.76,Norway1986,NaN,"78,693,253,276",20117,G.I. Generation
17876,Norway,1986,female,25-34 years,15,303600,4.94,Norway1986,NaN,"78,693,253,276",20117,Boomers
17877,Norway,1986,female,15-24 years,12,320000,3.75,Norway1986,NaN,"78,693,253,276",20117,Generation X
17878,Norway,1986,male,5-14 years,7,288100,2.43,Norway1986,NaN,"78,693,253,276",20117,Generation X
17879,Norway,1986,female,5-14 years,0,275100,0.00,Norway1986,NaN,"78,693,253,276",20117,Generation X

#### Suicidios en Noruega en 2014
Para calcular el total o la suma de los suicidios en Noruega en dicho aÃ±o uso el comando "sum()".

In [16]:
noruegos2014['suicides'].sum()

548

#### Suicidios en Albania en 1987
Para calcular el total o la suma de los suicidios en Noruega en dicho aÃ±o uso el comando "sum()".

In [17]:
noruegos1986['suicides'].sum()

579

### Albania en 1987
Siguiendo la misma lÃ³gica que en el caso de Noruega, Albania fue el "peor" paÃ­s econÃ³micamente hablando en el aÃ±o 1992, sin embargo se registran datos desde 1987.

In [18]:
albania1987 = data[(data["country"] == 'Albania') & (data["year"] == 1987)]

In [19]:
albania1987

,country,year,sex,age,suicides,population,suicides/100k pop,country-year,hdi,gdp_for_year ($),gdpc,generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers
5,Albania,1987,female,75+ years,1,35600,2.81,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
6,Albania,1987,female,35-54 years,6,278800,2.15,Albania1987,NaN,"2,156,624,900",796,Silent
7,Albania,1987,female,25-34 years,4,257200,1.56,Albania1987,NaN,"2,156,624,900",796,Boomers
8,Albania,1987,male,55-74 years,1,137500,0.73,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
9,Albania,1987,female,5-14 years,0,311000,0.00,Albania1987,NaN,"2,156,624,900",796,Generation X
10,Albania,1987,female,55-74 years,0,144600,0.00,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
11,Albania,1987,male,5-14 years,0,338200,0.00,Albania1987,NaN,"2,156,624,900",796,Generation X

### Albania al 2010
Es el ultimo aÃ±o del que se tiene informaciÃ³n de Albania

In [20]:
albania2010 = data[(data["country"] == 'Albania') & (data["year"] == 2010)]

In [21]:
albania2010

,country,year,sex,age,suicides,population,suicides/100k pop,country-year,hdi,gdp_for_year ($),gdpc,generation
252,Albania,2010,male,55-74 years,20,241852,8.27,Albania2010,0.722,"11,926,953,259",4359,Silent
253,Albania,2010,male,35-54 years,20,371611,5.38,Albania2010,0.722,"11,926,953,259",4359,Generation X
254,Albania,2010,male,25-34 years,9,179720,5.01,Albania2010,0.722,"11,926,953,259",4359,Generation X
255,Albania,2010,male,75+ years,2,50767,3.94,Albania2010,0.722,"11,926,953,259",4359,Silent
256,Albania,2010,male,15-24 years,10,279508,3.58,Albania2010,0.722,"11,926,953,259",4359,Millenials
257,Albania,2010,female,25-34 years,6,183579,3.27,Albania2010,0.722,"11,926,953,259",4359,Generation X
258,Albania,2010,female,75+ years,2,64415,3.10,Albania2010,0.722,"11,926,953,259",4359,Silent
259,Albania,2010,female,35-54 years,12,394593,3.04,Albania2010,0.722,"11,926,953,259",4359,Generation X
260,Albania,2010,female,55-74 years,7,241491,2.90,Albania2010,0.722,"11,926,953,259",4359,Silent
261,Albania,2010,female,15-24 years,6,263581,2.28,Albania2010,0.722,"11,926,953,259",4359,Millenials
262,Albania,2010,female,5-14 years,2,223969,0.89,Albania2010,0.722,"11,926,953,259",4359,Generation Z
263,Albania,2010,male,5-14 years,0,240939,0.00,Albania2010,0.722,"11,926,953,259",4359,Generation Z

#### Suicidios en Albania en 1987
Para calcular el total o la suma de los suicidios en Albania en dicho aÃ±o uso el comando "sum()".

In [22]:
albania1987['suicides'].sum()

73

#### Suicidios en Albania en 2010

In [23]:
albania2010['suicides'].sum()

96

### Primeras impresiones
Noruega del aÃ±o 1986 al 2014 (28 aÃ±os) redujo su nivel de suicidios en 31 (en dicho periodo Noruega sextuplicÃ³ su PBI), mientras que Albania en 23 aÃ±os aumento su nivel de suicidios en algo mÃ¡s de 21 (se debe tener en cuenta que Albania aproximadamente quintuplico su PBI). Lo cual es un primer instante nos indica que, en contra de la creencia popular, una mejor economÃ­a no conduce a una mayor felicidad o estabilidad mental (lo que suele decir y conocer en el argot popular como "felicidad").

### Jutando las 4 datas creadas
Usare el comando "merge" de la forma "outer" (ya que hare una union de dataframes) para juntar las 4 mini-bases de datos para poder realizar el grÃ¡fico pertinente. Lo hare en tres pasos y en cado uno usare el mismo comando y la misma logica.

### Junto a Noruega del aÃ±o 1986 con Noruega del aÃ±o 1986

In [24]:
noruega = pd.merge(noruegos2014,
                     noruegos1986,
                    how = 'outer', indicator = True)
noruega

,country,year,sex,age,suicides,population,suicides/100k pop,country-year,hdi,gdp_for_year ($),gdpc,generation,_merge
0,Norway,2014,male,75+ years,33,143089,23.06,Norway2014,0.944,"499,338,534,779",103443,Silent,left_only
1,Norway,2014,male,55-74 years,110,532578,20.65,Norway2014,0.944,"499,338,534,779",103443,Boomers,left_only
2,Norway,2014,male,35-54 years,147,732244,20.08,Norway2014,0.944,"499,338,534,779",103443,Generation X,left_only
3,Norway,2014,male,25-34 years,71,353943,20.06,Norway2014,0.944,"499,338,534,779",103443,Millenials,left_only
4,Norway,2014,male,15-24 years,38,344245,11.04,Norway2014,0.944,"499,338,534,779",103443,Millenials,left_only
5,Norway,2014,female,55-74 years,51,533630,9.56,Norway2014,0.944,"499,338,534,779",103443,Boomers,left_only
6,Norway,2014,female,35-54 years,51,688993,7.40,Norway2014,0.944,"499,338,534,779",103443,Generation X,left_only
7,Norway,2014,female,25-34 years,20,337592,5.92,Norway2014,0.944,"499,338,534,779",103443,Millenials,left_only
8,Norway,2014,female,15-24 years,17,325164,5.23,Norway2014,0.944,"499,338,534,779",103443,Millenials,left_only
9,Norway,2014,female,75+ years,7,214335,3.27,Norway2014,0.944,"499,338,534,779",103443,Silent,left_only
10,Norway,2014,male,5-14 years,2,317878,0.63,Norway2014,0.944,"499,338,534,779",103443,Generation Z,left_only
11,Norway,2014,female,5-14 years,1,303487,0.33,Norway2014,0.944,"499,338,534,779",103443,Generation Z,left_only
12,Norway,1986,male,35-54 years,137,500900,27.35,Norway1986,NaN,"78,693,253,276",20117,Silent,right_only
13,Norway,1986,male,25-34 years,86,318200,27.03,Norway1986,NaN,"78,693,253,276",20117,Boomers,right_only
14,Norway,1986,male,55-74 years,101,383100,26.36,Norway1986,NaN,"78,693,253,276",20117,G.I. Generation,right_only
15,Norway,1986,male,15-24 years,69,336000,20.54,Norway1986,NaN,"78,693,253,276",20117,Generation X,right_only
16,Norway,1986,male,75+ years,19,102800,18.48,Norway1986,NaN,"78,693,253,276",20117,G.I. Generation,right_only
17,Norway,1986,female,35-54 years,67,480100,13.96,Norway1986,NaN,"78,693,253,276",20117,Silent,right_only
18,Norway,1986,female,55-74 years,56,430100,13.02,Norway1986,NaN,"78,693,253,276",20117,G.I. Generation,right_only
19,Norway,1986,female,75+ years,10,173700,5.76,Norway1986,NaN,"78,693,253,276",20117,G.I. Generation,right_only
20,Norway,1986,female,25-34 years,15,303600,4.94,Norway1986,NaN,"78,693,253,276",20117,Boomers,right_only
21,Norway,1986,female,15-24 years,12,320000,3.75,Norway1986,NaN,"78,693,253,276",20117,Generation X,right_only
22,Norway,1986,male,5-14 years,7,288100,2.43,Norway1986,NaN,"78,693,253,276",20117,Generation X,right_only
23,Norway,1986,female,5-14 years,0,275100,0.00,Norway1986,NaN,"78,693,253,276",20117,Generation X,right_only

### Junto a Albania de 1987 con Albania al aÃ±o 2010

In [25]:
albania = pd.merge(albania1987,
                     albania2010,
                    how = 'outer', indicator = True)
albania

,country,year,sex,age,suicides,population,suicides/100k pop,country-year,hdi,gdp_for_year ($),gdpc,generation,_merge
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X,left_only
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent,left_only
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X,left_only
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation,left_only
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers,left_only
5,Albania,1987,female,75+ years,1,35600,2.81,Albania1987,NaN,"2,156,624,900",796,G.I. Generation,left_only
6,Albania,1987,female,35-54 years,6,278800,2.15,Albania1987,NaN,"2,156,624,900",796,Silent,left_only
7,Albania,1987,female,25-34 years,4,257200,1.56,Albania1987,NaN,"2,156,624,900",796,Boomers,left_only
8,Albania,1987,male,55-74 years,1,137500,0.73,Albania1987,NaN,"2,156,624,900",796,G.I. Generation,left_only
9,Albania,1987,female,5-14 years,0,311000,0.00,Albania1987,NaN,"2,156,624,900",796,Generation X,left_only
10,Albania,1987,female,55-74 years,0,144600,0.00,Albania1987,NaN,"2,156,624,900",796,G.I. Generation,left_only
11,Albania,1987,male,5-14 years,0,338200,0.00,Albania1987,NaN,"2,156,624,900",796,Generation X,left_only
12,Albania,2010,male,55-74 years,20,241852,8.27,Albania2010,0.722,"11,926,953,259",4359,Silent,right_only
13,Albania,2010,male,35-54 years,20,371611,5.38,Albania2010,0.722,"11,926,953,259",4359,Generation X,right_only
14,Albania,2010,male,25-34 years,9,179720,5.01,Albania2010,0.722,"11,926,953,259",4359,Generation X,right_only
15,Albania,2010,male,75+ years,2,50767,3.94,Albania2010,0.722,"11,926,953,259",4359,Silent,right_only
16,Albania,2010,male,15-24 years,10,279508,3.58,Albania2010,0.722,"11,926,953,259",4359,Millenials,right_only
17,Albania,2010,female,25-34 years,6,183579,3.27,Albania2010,0.722,"11,926,953,259",4359,Generation X,right_only
18,Albania,2010,female,75+ years,2,64415,3.10,Albania2010,0.722,"11,926,953,259",4359,Silent,right_only
19,Albania,2010,female,35-54 years,12,394593,3.04,Albania2010,0.722,"11,926,953,259",4359,Generation X,right_only
20,Albania,2010,female,55-74 years,7,241491,2.90,Albania2010,0.722,"11,926,953,259",4359,Silent,right_only
21,Albania,2010,female,15-24 years,6,263581,2.28,Albania2010,0.722,"11,926,953,259",4359,Millenials,right_only
22,Albania,2010,female,5-14 years,2,223969,0.89,Albania2010,0.722,"11,926,953,259",4359,Generation Z,right_only
23,Albania,2010,male,5-14 years,0,240939,0.00,Albania2010,0.722,"11,926,953,259",4359,Generation Z,right_only

### Finalmente: Junto a Noruega y Albania para los 4 aÃ±os

In [26]:
paises = pd.merge(noruega,
                  albania,
                    how = 'outer', indicator = False)
paises

,country,year,sex,age,suicides,population,suicides/100k pop,country-year,hdi,gdp_for_year ($),gdpc,generation,_merge
0,Norway,2014,male,75+ years,33,143089,23.06,Norway2014,0.944,"499,338,534,779",103443,Silent,left_only
1,Norway,2014,male,55-74 years,110,532578,20.65,Norway2014,0.944,"499,338,534,779",103443,Boomers,left_only
2,Norway,2014,male,35-54 years,147,732244,20.08,Norway2014,0.944,"499,338,534,779",103443,Generation X,left_only
3,Norway,2014,male,25-34 years,71,353943,20.06,Norway2014,0.944,"499,338,534,779",103443,Millenials,left_only
4,Norway,2014,male,15-24 years,38,344245,11.04,Norway2014,0.944,"499,338,534,779",103443,Millenials,left_only
5,Norway,2014,female,55-74 years,51,533630,9.56,Norway2014,0.944,"499,338,534,779",103443,Boomers,left_only
6,Norway,2014,female,35-54 years,51,688993,7.40,Norway2014,0.944,"499,338,534,779",103443,Generation X,left_only
7,Norway,2014,female,25-34 years,20,337592,5.92,Norway2014,0.944,"499,338,534,779",103443,Millenials,left_only
8,Norway,2014,female,15-24 years,17,325164,5.23,Norway2014,0.944,"499,338,534,779",103443,Millenials,left_only
9,Norway,2014,female,75+ years,7,214335,3.27,Norway2014,0.944,"499,338,534,779",103443,Silent,left_only
10,Norway,2014,male,5-14 years,2,317878,0.63,Norway2014,0.944,"499,338,534,779",103443,Generation Z,left_only
11,Norway,2014,female,5-14 years,1,303487,0.33,Norway2014,0.944,"499,338,534,779",103443,Generation Z,left_only
12,Norway,1986,male,35-54 years,137,500900,27.35,Norway1986,NaN,"78,693,253,276",20117,Silent,right_only
13,Norway,1986,male,25-34 years,86,318200,27.03,Norway1986,NaN,"78,693,253,276",20117,Boomers,right_only
14,Norway,1986,male,55-74 years,101,383100,26.36,Norway1986,NaN,"78,693,253,276",20117,G.I. Generation,right_only
15,Norway,1986,male,15-24 years,69,336000,20.54,Norway1986,NaN,"78,693,253,276",20117,Generation X,right_only
16,Norway,1986,male,75+ years,19,102800,18.48,Norway1986,NaN,"78,693,253,276",20117,G.I. Generation,right_only
17,Norway,1986,female,35-54 years,67,480100,13.96,Norway1986,NaN,"78,693,253,276",20117,Silent,right_only
18,Norway,1986,female,55-74 years,56,430100,13.02,Norway1986,NaN,"78,693,253,276",20117,G.I. Generation,right_only
19,Norway,1986,female,75+ years,10,173700,5.76,Norway1986,NaN,"78,693,253,276",20117,G.I. Generation,right_only
20,Norway,1986,female,25-34 years,15,303600,4.94,Norway1986,NaN,"78,693,253,276",20117,Boomers,right_only
21,Norway,1986,female,15-24 years,12,320000,3.75,Norway1986,NaN,"78,693,253,276",20117,Generation X,right_only
22,Norway,1986,male,5-14 years,7,288100,2.43,Norway1986,NaN,"78,693,253,276",20117,Generation X,right_only
23,Norway,1986,female,5-14 years,0,275100,0.00,Norway1986,NaN,"78,693,253,276",20117,Generation X,right_only
24,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X,left_only
25,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent,left_only
26,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X,left_only
27,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation,left_only
28,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers,left_only
29,Albania,1987,female,75+ years,1,35600,2.81,Albania1987,NaN,"2,156,624,900",796,G.I. Generation,left_only
30,Albania,1987,female,35-54 years,6,278800,2.15,Albania1987,NaN,"2,156,624,900",796,Silent,left_only
31,Albania,1987,female,25-34 years,4,257200,1.56,Albania1987,NaN,"2,156,624,900",796,Boomers,left_only
32,Albania,1987,male,55-74 years,1,137500,0.73,Albania1987,NaN,"2,156,624,900",796,G.I. Generation,left_only
33,Albania,1987,female,5-14 years,0,311000,0.00,Albania1987,NaN,"2,156,624,900",796,Generation X,left_only
34,Albania,1987,female,55-74 years,0,144600,0.00,Albania1987,NaN,"2,156,624,900",796,G.I. Generation,left_only
35,Albania,1987,male,5-14 years,0,338200,0.00,Albania1987,NaN,"2,156,624,900",796,Generation X,left_only
36,Albania,2010,male,55-74 years,20,241852,8.27,Albania2010,0.722,"11,926,953,259",4359,Silent,right_only
37,Albania,2010,male,35-54 years,20,371611,5.38,Albania2010,0.722,"11,926,953,259",4359,Generation X,right_only
38,Albania,2010,male,25-34 years,9,179720,5.01,Albania2010,0.722,"11,926,953,259",4359,Generation X,right_only
39,Albania,2010,male,75+ years,2,50767,3.94,Albania2010,0.722,"11,926,953,259",4359,Silent,right_only
40,Albania,2010,male,15-24 years,10,279508,3.58,Albania2010,0.722,"11,926,953,259",4359,Millenials,right_only
41,Albania,2010,female,25-34 years,6,183579,3.27,Albania2010,0.722,"11,926,953,259",4359,Generation X,right_only
42,Albania,2010,female,75+ years,2,64415,3.10,Albania2010,0.722,"11,926,953,259",4359,Silent,right_only
43,Albania,2010,female,35-54 years,12,394593,3.04,Albania2010,0.722,"11,926,953,259",4359,Generation X,right_only
44,Albania,2010,female,55-74 years,7,241491,2.90,Albania2010,0.722,"11,926,953,259",4359,Silent,right_only
45,Albania,2010,female,15-24 years,6,263581,2.28,Albania2010,0.722,"11,926,953,259",4359,Millenials,right_only
46,Albania,2010,female,5-14 years,2,223969,0.89,Albania2010,0.722,"11,926,953,259",4359,Generation Z,right_only
47,Albania,2010,male,5-14 years,0,240939,0.00,Albania2010,0.722,"11,926,953,259",4359,Generation Z,right_only

### Graficos
Usaremos el paquete "Altair" para hacer los graficos.

In [27]:
import altair as alt

#### Grafico de dispersion
Para corroborar lo que dije mÃ¡s arriba (que no hay ninguna relaciÃ³n aparente entre el PBI per capita y los suicidios) uso el comando "mark_point()".

In [28]:
alt.Chart(paises).mark_point(color='green').encode(
    x = alt.X("gdpc"),
    y = alt.Y("suicides"),
    color = alt.Color("country", 
            legend=alt.Legend(orient='bottom', titleOrient='left')),
    column = alt.Column("country")
    ).properties(width=300, height=300)

alt.Chart(...)

Se puede ver que el grafico no tiene ni pendiente negativa ni positiva por lo que se puede decir que no hay ninguna correlaciÃ³n entre el PBI per capita y los suicidios ("felicidad").

#### Grafico de barras
Para ver el numero de suicidios por sexo y paÃ­s. Uso el comando "mark_bar()".

In [29]:
alt.Chart(paises).mark_bar().encode(
    x = alt.X("sex"),
    y = alt.Y("suicides"),
    color = alt.Color("country", 
            legend=alt.Legend(orient='bottom', titleOrient='left')),
    column = alt.Column("country")
    ).properties(width=300, height=300)

alt.Chart(...)

Asimismo, a partir del grafico de barras se puede observar que el sexo con mas numeros de suicidios tanto en el "peor" (Albania) y "mejor" (Noruega) pais es el masculino.